//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaComponente.DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dboPruebaComponenteEntities : DbContext
    {
        public dboPruebaComponenteEntities()
            : base("name=dboPruebaComponenteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LogTransaccion> LogTransaccion { get; set; }
        public virtual DbSet<UsuarioApi> UsuarioApi { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
