//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaComponente.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTransaccion
    {
        public long Id { get; set; }
        public string Metodo { get; set; }
        public string JsonEntrada { get; set; }
        public string JsonSalida { get; set; }
        public long Codigo { get; set; }
        public string MensajeError { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
