//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaComponente.Web.CrudServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaUsuarioDTO", Namespace="http://schemas.datacontract.org/2004/07/PruebaComponente.BLL.DTO")]
    [System.SerializableAttribute()]
    public partial class ConsultaUsuarioDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestCrearUsuario", Namespace="http://schemas.datacontract.org/2004/07/PruebaComponente.BLL.DTO")]
    [System.SerializableAttribute()]
    public partial class RequestCrearUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioDTO", Namespace="http://schemas.datacontract.org/2004/07/PruebaComponente.BLL.DTO")]
    [System.SerializableAttribute()]
    public partial class UsuarioDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((this.RespuestaField.Equals(value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestEditarUsuario", Namespace="http://schemas.datacontract.org/2004/07/PruebaComponente.BLL.DTO")]
    [System.SerializableAttribute()]
    public partial class RequestEditarUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CrudServiceReference.ICrudService")]
    public interface ICrudService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/Consulta", ReplyAction="http://tempuri.org/ICrudService/ConsultaResponse")]
        PruebaComponente.Web.CrudServiceReference.ConsultaUsuarioDTO[] Consulta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/Consulta", ReplyAction="http://tempuri.org/ICrudService/ConsultaResponse")]
        System.Threading.Tasks.Task<PruebaComponente.Web.CrudServiceReference.ConsultaUsuarioDTO[]> ConsultaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/ConsultaId", ReplyAction="http://tempuri.org/ICrudService/ConsultaIdResponse")]
        PruebaComponente.Web.CrudServiceReference.ConsultaUsuarioDTO ConsultaId(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/ConsultaId", ReplyAction="http://tempuri.org/ICrudService/ConsultaIdResponse")]
        System.Threading.Tasks.Task<PruebaComponente.Web.CrudServiceReference.ConsultaUsuarioDTO> ConsultaIdAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/Crear", ReplyAction="http://tempuri.org/ICrudService/CrearResponse")]
        PruebaComponente.Web.CrudServiceReference.UsuarioDTO Crear(PruebaComponente.Web.CrudServiceReference.RequestCrearUsuario request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/Crear", ReplyAction="http://tempuri.org/ICrudService/CrearResponse")]
        System.Threading.Tasks.Task<PruebaComponente.Web.CrudServiceReference.UsuarioDTO> CrearAsync(PruebaComponente.Web.CrudServiceReference.RequestCrearUsuario request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/Editar", ReplyAction="http://tempuri.org/ICrudService/EditarResponse")]
        PruebaComponente.Web.CrudServiceReference.UsuarioDTO Editar(PruebaComponente.Web.CrudServiceReference.RequestEditarUsuario request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/Editar", ReplyAction="http://tempuri.org/ICrudService/EditarResponse")]
        System.Threading.Tasks.Task<PruebaComponente.Web.CrudServiceReference.UsuarioDTO> EditarAsync(PruebaComponente.Web.CrudServiceReference.RequestEditarUsuario request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/Eliminar", ReplyAction="http://tempuri.org/ICrudService/EliminarResponse")]
        PruebaComponente.Web.CrudServiceReference.UsuarioDTO Eliminar(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/Eliminar", ReplyAction="http://tempuri.org/ICrudService/EliminarResponse")]
        System.Threading.Tasks.Task<PruebaComponente.Web.CrudServiceReference.UsuarioDTO> EliminarAsync(long id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrudServiceChannel : PruebaComponente.Web.CrudServiceReference.ICrudService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrudServiceClient : System.ServiceModel.ClientBase<PruebaComponente.Web.CrudServiceReference.ICrudService>, PruebaComponente.Web.CrudServiceReference.ICrudService {
        
        public CrudServiceClient() {
        }
        
        public CrudServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrudServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrudServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrudServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PruebaComponente.Web.CrudServiceReference.ConsultaUsuarioDTO[] Consulta() {
            return base.Channel.Consulta();
        }
        
        public System.Threading.Tasks.Task<PruebaComponente.Web.CrudServiceReference.ConsultaUsuarioDTO[]> ConsultaAsync() {
            return base.Channel.ConsultaAsync();
        }
        
        public PruebaComponente.Web.CrudServiceReference.ConsultaUsuarioDTO ConsultaId(long id) {
            return base.Channel.ConsultaId(id);
        }
        
        public System.Threading.Tasks.Task<PruebaComponente.Web.CrudServiceReference.ConsultaUsuarioDTO> ConsultaIdAsync(long id) {
            return base.Channel.ConsultaIdAsync(id);
        }
        
        public PruebaComponente.Web.CrudServiceReference.UsuarioDTO Crear(PruebaComponente.Web.CrudServiceReference.RequestCrearUsuario request) {
            return base.Channel.Crear(request);
        }
        
        public System.Threading.Tasks.Task<PruebaComponente.Web.CrudServiceReference.UsuarioDTO> CrearAsync(PruebaComponente.Web.CrudServiceReference.RequestCrearUsuario request) {
            return base.Channel.CrearAsync(request);
        }
        
        public PruebaComponente.Web.CrudServiceReference.UsuarioDTO Editar(PruebaComponente.Web.CrudServiceReference.RequestEditarUsuario request) {
            return base.Channel.Editar(request);
        }
        
        public System.Threading.Tasks.Task<PruebaComponente.Web.CrudServiceReference.UsuarioDTO> EditarAsync(PruebaComponente.Web.CrudServiceReference.RequestEditarUsuario request) {
            return base.Channel.EditarAsync(request);
        }
        
        public PruebaComponente.Web.CrudServiceReference.UsuarioDTO Eliminar(long id) {
            return base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task<PruebaComponente.Web.CrudServiceReference.UsuarioDTO> EliminarAsync(long id) {
            return base.Channel.EliminarAsync(id);
        }
    }
}
